# Generated by Django 4.2.5 on 2023-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
