# Generated by Django 4.2.5 on 2023-09-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_users_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='matricula',
        ),
    ]
